In [1]:
import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np
import datetime as dt
from IPython.display import display
import glob
pd.set_option('display.max_columns',200)

In [2]:
def xml2df(xml_data):
    root = ET.XML(xml_data) # element tree
    all_records = []
    for i, child in enumerate(root):
        record = {}
        for subchild in child:
            record[subchild.tag] = subchild.text
        all_records.append(record)
    df = pd.DataFrame(all_records)
    return df

In [3]:
# import the xml files into one dataframe
_d = pd.DataFrame()

filenames = sorted(glob.glob('./data/201*.xml'))
filenames = filenames[0:6]

for f in filenames:
    print(f)
    xml_data = open(f).read()
    _x = xml2df(xml_data)
    _d = _d.append(_x)

./data/2011.xml
./data/2012.xml
./data/2013.xml
./data/2014.xml

/home/david/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

./data/2015.xml
./data/2016.xml

In [4]:
# Review the shape of the Dataframe
_d.shape

(720370, 103)

In [5]:
_d.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 720370 entries, 0 to 117425
Columns: 103 entries, AGENT_APP_HOUR to WATER
dtypes: float64(1), object(102)
memory usage: 3.0 GB

In [6]:
_d.head()

,AGENT_APP_HOUR,AGENT_APP_MIN,AGENT_APP_SEC,AGE_OF_STRUCTURE,AID_TO_FROM_OTHER_DEPTS,ALARM_TO_FD,AREA_OF_ORIGIN,ARRIVE_DATE,BLD_HEIGHT,BLD_STATUS,CANUTEC,CIVILIAN_FIRE_FATALITY,CIVILIAN_FIRE_INJURY,CIV_EVACUATION,CIV_EVACUATION_REASON_1,CIV_EVACUATION_REASON_2,CIV_FIRE_CONTROL,COMPLEX,CONTROL_DATE,CONTROL_HOUR,CONTROL_MIN,CONTROL_SEC,CROSS_STREET,DISPATCH_DATE,DISPATCH_HOUR,DISPATCH_MIN,DISPATCH_SEC,EMS,ESA,EST_KM,EST_LOSS,EST_NUM_PERSONS_DISPLACED,EST_VALUE_AT_RISK,EVENT_ALARM_LEVEL,EVENT_TYPE,EVENT_TYPE_CD,EXTENT_FIRE,EXTENT_SMOKE,FD_STATION,FF_FATALITIES,FF_INJURIES,FIRE_ALARM_SYSTEM_IMPACT,FIRE_ALARM_SYSTEM_OPERATION,FIRE_ALARM_SYSTEM_PRESENCE,FIRE_CONTROL,FIRE_DEPT_INCIDENT,FSA,FUEL_OF_IGNITION_SOURCE,GAS,HYDRO,IGNITION_SOURCE,INCIDENT_DATE,INCIDENT_NUMBER,INITIAL_CALL_HOUR,INITIAL_CALL_MIN,INITIAL_CALL_SEC,INITIAL_DETECTION,INITIAL_UNIT_PERSONNEL,INSURANCE_ESTIMATE,LEVEL_OF_ORIGIN,MAIN_STREET,MOE,MOL,MUNICIPAL_BUILDING_OFFICE,MUNICIPAL_HEALTH_OFFICE,MUNICIPAL_POLICE,OBJECT_OR_MATERIAL_FIRST_IGNITED,OCC_STATUS,OCC_TYPE,OFM_INVESTIGATIONS_CONTACTED,ONSCENE_HOUR,ONSCENE_MIN,ONSCENE_SEC,OPP,OTHER,PHYSICAL_CONDITION_1,PHYSICAL_CONDITION_2,PHYSICAL_CONDITION_3,POSSIBLE_BUSINESS_IMPACT,POSSIBLE_CAUSE,PROPERTY,RESCUED_ADULTS,RESCUED_CHILDREN,RESCUED_SENIORS,RESCUES,RESPONDING_UNITS,RESPONSE_TYPE,RespondingUnits,SMOKE_ALARM_FAILURE_TO_OPERATE,SMOKE_ALARM_IMPACT_ON_EVAC,SMOKE_ALARM_IMPACT_ON_NUM_EVAC,SMOKE_ALARM_ON_ALL_FLOORS,SMOKE_ALARM_OTHER_FLOOR_PRESENCE,SMOKE_ALARM_PRESENCE_AND_OPERATION_MAIN_FLOOR,SMOKE_ALARM_TYPE,SPRINKLER_SYSTEM_ACTIVATION,SPRINKLER_SYSTEM_PRESENCE,STATUS_ON_ARRIVAL,TOTAL_NUM_PERSONNEL,TSSA,VEH_FUEL,VEH_PURPOSE,WATER
0,None,None,None,None,4,03,None,2011-01-01 00:10:02,0,None,,0,0,None,None,None,None,None,None,None,None,None,None,2011-01-01 00:04:13,0,4,13,,,1,0,0,None,NaN,Medical,MEB,None,None,F11000010000,0,0,None,None,None,None,NaN,M6N,None,,,None,01/01/2011,F11000010,0,3,43,None,4,None,None,None,,,,,,None,None,None,0,0,10,2,,,None,None,None,None,None,301,0,0,0,0,1,89,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
1,None,None,None,None,4,01,None,2011-01-01 00:09:02,0,None,,0,0,None,None,None,None,None,None,None,None,None,LAWRENCE AVE E,2011-01-01 00:04:46,0,4,46,,,1,0,0,None,NaN,Carbon Monoxide - Non Medical,CONM,None,None,F11000011000,0,0,None,None,None,None,NaN,None,None,,,None,01/01/2011,F11000011,0,3,55,None,4,None,None,MOUNT PLEASANT RD,,,,,,None,None,None,0,0,9,2,,,None,None,None,None,None,301,0,0,0,0,1,38,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
2,None,None,None,None,4,03,None,2011-01-01 00:09:34,0,None,,0,0,None,None,None,None,None,None,None,None,None,None,2011-01-01 00:05:50,0,5,50,,,1,0,0,None,NaN,Medical,MEPI,None,None,F11000012000,0,0,None,None,None,None,NaN,M4M,None,,,None,01/01/2011,F11000012,0,5,3,None,4,None,None,None,,,,,,None,None,None,0,0,9,34,,,None,None,None,None,None,302,0,0,0,0,1,89,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
3,None,None,None,None,4,01,None,2011-01-01 00:10:46,0,None,,0,0,None,None,None,None,None,None,None,None,None,SYLVAN AVE,2011-01-01 00:06:33,0,6,33,,,2,0,0,None,NaN,Fire - Grass/Rubbish,FIG,None,None,F11000013000,0,0,None,None,None,None,NaN,None,None,,,None,01/01/2011,F11000013,0,4,46,None,4,None,None,DUFFERIN ST,,,,,,None,None,None,0,0,10,46,,,None,None,None,None,None,861,0,0,0,0,1,03,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
4,None,None,None,None,1,05,None,2011-01-01 00:11:03,0,None,,0,0,None,None,None,None,None,None,None,None,None,SAN VAROWAY,2011-01-01 00:06:41,0,6,41,,,1,0,0,None,NaN,Alarm Highrise Residential,FAHR,None,None,F11000014000,0,0,None,None,None,None,NaN,None,None,,,None,01/01/2011,F11000014,0,6,7,None,4,None,None,SAN ROMANOWAY,,,,,,None,None,None,0,0,11,3,,,None,None,None,None,None,323,0,0,0,0,4,33,NaN,None,None,0,None,None,None,None,None,None,None,14,,None,None,None

In [7]:
# Remove any whitespaces from the names
_d.columns = _d.columns.str.replace(' ', '')
# Set names to lower case
_d.columns = _d.columns.str.lower()

In [8]:
# Deterime the number of nan per column
#_d.isna().sum()

agent_app_hour                                   708040
agent_app_min                                    708040
agent_app_sec                                    708040
age_of_structure                                 711589
aid_to_from_other_depts                               0
alarm_to_fd                                           1
area_of_origin                                   708040
arrive_date                                       16802
bld_height                                            0
bld_status                                       711589
canutec                                               0
civilian_fire_fatality                                0
civilian_fire_injury                                  0
civ_evacuation                                   708041
civ_evacuation_reason_1                          708041
civ_evacuation_reason_2                          720265
civ_fire_control                                 708041
complex                                          711589
control_date                                     478833
control_hour                                     707821
control_min                                      707821
control_sec                                      707821
cross_street                                     390349
dispatch_date                                       691
dispatch_hour                                       177
dispatch_min                                        177
dispatch_sec                                        177
ems                                                   0
esa                                                   0
est_km                                                0
                                                  ...
opp                                                   0
other                                                 0
physical_condition_1                             708041
physical_condition_2                             720323
physical_condition_3                             720363
possible_business_impact                         711585
possible_cause                                   708040
property                                           9863
rescued_adults                                        0
rescued_children                                      0
rescued_seniors                                       0
rescues                                               0
responding_units                                     32
response_type                                         0
respondingunits                                  720370
smoke_alarm_failure_to_operate                   711589
smoke_alarm_impact_on_evac                       711589
smoke_alarm_impact_on_num_evac                        0
smoke_alarm_on_all_floors                        711589
smoke_alarm_other_floor_presence                 711589
smoke_alarm_presence_and_operation_main_floor    711589
smoke_alarm_type                                 711589
sprinkler_system_activation                      711589
sprinkler_system_presence                        711589
status_on_arrival                                708040
total_num_personnel                                   0
tssa                                                  0
veh_fuel                                         718631
veh_purpose                                      718631
water                                            708040
Length: 103, dtype: int64

In [9]:
_d.head()

,agent_app_hour,agent_app_min,agent_app_sec,age_of_structure,aid_to_from_other_depts,alarm_to_fd,area_of_origin,arrive_date,bld_height,bld_status,canutec,civilian_fire_fatality,civilian_fire_injury,civ_evacuation,civ_evacuation_reason_1,civ_evacuation_reason_2,civ_fire_control,complex,control_date,control_hour,control_min,control_sec,cross_street,dispatch_date,dispatch_hour,dispatch_min,dispatch_sec,ems,esa,est_km,est_loss,est_num_persons_displaced,est_value_at_risk,event_alarm_level,event_type,event_type_cd,extent_fire,extent_smoke,fd_station,ff_fatalities,ff_injuries,fire_alarm_system_impact,fire_alarm_system_operation,fire_alarm_system_presence,fire_control,fire_dept_incident,fsa,fuel_of_ignition_source,gas,hydro,ignition_source,incident_date,incident_number,initial_call_hour,initial_call_min,initial_call_sec,initial_detection,initial_unit_personnel,insurance_estimate,level_of_origin,main_street,moe,mol,municipal_building_office,municipal_health_office,municipal_police,object_or_material_first_ignited,occ_status,occ_type,ofm_investigations_contacted,onscene_hour,onscene_min,onscene_sec,opp,other,physical_condition_1,physical_condition_2,physical_condition_3,possible_business_impact,possible_cause,property,rescued_adults,rescued_children,rescued_seniors,rescues,responding_units,response_type,respondingunits,smoke_alarm_failure_to_operate,smoke_alarm_impact_on_evac,smoke_alarm_impact_on_num_evac,smoke_alarm_on_all_floors,smoke_alarm_other_floor_presence,smoke_alarm_presence_and_operation_main_floor,smoke_alarm_type,sprinkler_system_activation,sprinkler_system_presence,status_on_arrival,total_num_personnel,tssa,veh_fuel,veh_purpose,water
0,None,None,None,None,4,03,None,2011-01-01 00:10:02,0,None,,0,0,None,None,None,None,None,None,None,None,None,None,2011-01-01 00:04:13,0,4,13,,,1,0,0,None,NaN,Medical,MEB,None,None,F11000010000,0,0,None,None,None,None,NaN,M6N,None,,,None,01/01/2011,F11000010,0,3,43,None,4,None,None,None,,,,,,None,None,None,0,0,10,2,,,None,None,None,None,None,301,0,0,0,0,1,89,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
1,None,None,None,None,4,01,None,2011-01-01 00:09:02,0,None,,0,0,None,None,None,None,None,None,None,None,None,LAWRENCE AVE E,2011-01-01 00:04:46,0,4,46,,,1,0,0,None,NaN,Carbon Monoxide - Non Medical,CONM,None,None,F11000011000,0,0,None,None,None,None,NaN,None,None,,,None,01/01/2011,F11000011,0,3,55,None,4,None,None,MOUNT PLEASANT RD,,,,,,None,None,None,0,0,9,2,,,None,None,None,None,None,301,0,0,0,0,1,38,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
2,None,None,None,None,4,03,None,2011-01-01 00:09:34,0,None,,0,0,None,None,None,None,None,None,None,None,None,None,2011-01-01 00:05:50,0,5,50,,,1,0,0,None,NaN,Medical,MEPI,None,None,F11000012000,0,0,None,None,None,None,NaN,M4M,None,,,None,01/01/2011,F11000012,0,5,3,None,4,None,None,None,,,,,,None,None,None,0,0,9,34,,,None,None,None,None,None,302,0,0,0,0,1,89,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
3,None,None,None,None,4,01,None,2011-01-01 00:10:46,0,None,,0,0,None,None,None,None,None,None,None,None,None,SYLVAN AVE,2011-01-01 00:06:33,0,6,33,,,2,0,0,None,NaN,Fire - Grass/Rubbish,FIG,None,None,F11000013000,0,0,None,None,None,None,NaN,None,None,,,None,01/01/2011,F11000013,0,4,46,None,4,None,None,DUFFERIN ST,,,,,,None,None,None,0,0,10,46,,,None,None,None,None,None,861,0,0,0,0,1,03,NaN,None,None,0,None,None,None,None,None,None,None,4,,None,None,None
4,None,None,None,None,1,05,None,2011-01-01 00:11:03,0,None,,0,0,None,None,None,None,None,None,None,None,None,SAN VAROWAY,2011-01-01 00:06:41,0,6,41,,,1,0,0,None,NaN,Alarm Highrise Residential,FAHR,None,None,F11000014000,0,0,None,None,None,None,NaN,None,None,,,None,01/01/2011,F11000014,0,6,7,None,4,None,None,SAN ROMANOWAY,,,,,,None,None,None,0,0,11,3,,,None,None,None,None,None,323,0,0,0,0,4,33,NaN,None,None,0,None,None,None,None,None,None,None,14,,None,None,None

In [10]:
#list(_d)

In [11]:
# Deterime the pecentage of nan per column
#_d.isna().sum()/len(_d)*100

In [12]:
# remove columns that have more than 90% nan or 105683 nan rows
#df = _d.loc[:, _d.isnull().sum() < 0.9*_d.shape[0]]

In [13]:
df = _d[['civilian_fire_fatality','civilian_fire_injury','civ_evacuation','fd_station',\
         'ff_fatalities','ff_injuries','incident_date','incident_number','occ_status',\
         'occ_type','rescued_adults','rescued_children','rescued_seniors','rescues','responding_units',\
         'response_type','respondingunits','status_on_arrival','total_num_personnel']]

# set incident as indext
df = df.set_index('incident_number')

In [14]:
# Review the new shape of the Dataframe
df.head()

,civilian_fire_fatality,civilian_fire_injury,civ_evacuation,fd_station,ff_fatalities,ff_injuries,incident_date,occ_status,occ_type,rescued_adults,rescued_children,rescued_seniors,rescues,responding_units,response_type,respondingunits,status_on_arrival,total_num_personnel
incident_number,,,,,,,,,,,,,,,,,,
F11000010,0,0,None,F11000010000,0,0,01/01/2011,None,None,0,0,0,0,1,89,NaN,None,4
F11000011,0,0,None,F11000011000,0,0,01/01/2011,None,None,0,0,0,0,1,38,NaN,None,4
F11000012,0,0,None,F11000012000,0,0,01/01/2011,None,None,0,0,0,0,1,89,NaN,None,4
F11000013,0,0,None,F11000013000,0,0,01/01/2011,None,None,0,0,0,0,1,03,NaN,None,4
F11000014,0,0,None,F11000014000,0,0,01/01/2011,None,None,0,0,0,0,4,33,NaN,None,14

In [15]:
# Delete orignal Dataframe _d
del _d

In [16]:
# Fill any NAN data withthe average of the column
for key, value in df.iteritems():
    if np.issubdtype(df[key].dtype, np.number) == True:
        _v = df[key].mean()
        df[key].fillna(value=_v)

In [17]:
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 720370 entries, F11000010 to F16122097
Data columns (total 18 columns):
civilian_fire_fatality    720370 non-null object
civilian_fire_injury      720370 non-null object
civ_evacuation            12329 non-null object
fd_station                720370 non-null object
ff_fatalities             720370 non-null object
ff_injuries               720370 non-null object
incident_date             720370 non-null object
occ_status                8781 non-null object
occ_type                  8781 non-null object
rescued_adults            720370 non-null object
rescued_children          720370 non-null object
rescued_seniors           720370 non-null object
rescues                   720370 non-null object
responding_units          720338 non-null object
response_type             720370 non-null object
respondingunits           0 non-null float64
status_on_arrival         12330 non-null object
total_num_personnel       720370 non-null object
dtypes: float64(1), object(17)
memory usage: 701.2 MB

In [18]:
# Change dates from object to date time in int64 unix timestamp
df['incident_date'] = pd.to_datetime(df['incident_date'])

In [19]:
df.head()

,civilian_fire_fatality,civilian_fire_injury,civ_evacuation,fd_station,ff_fatalities,ff_injuries,incident_date,occ_status,occ_type,rescued_adults,rescued_children,rescued_seniors,rescues,responding_units,response_type,respondingunits,status_on_arrival,total_num_personnel
incident_number,,,,,,,,,,,,,,,,,,
F11000010,0,0,None,F11000010000,0,0,2011-01-01,None,None,0,0,0,0,1,89,NaN,None,4
F11000011,0,0,None,F11000011000,0,0,2011-01-01,None,None,0,0,0,0,1,38,NaN,None,4
F11000012,0,0,None,F11000012000,0,0,2011-01-01,None,None,0,0,0,0,1,89,NaN,None,4
F11000013,0,0,None,F11000013000,0,0,2011-01-01,None,None,0,0,0,0,1,03,NaN,None,4
F11000014,0,0,None,F11000014000,0,0,2011-01-01,None,None,0,0,0,0,4,33,NaN,None,14

In [20]:
df.to_csv('./data/TFSDataSet.csv')